<!-- using the img srcset we specify different quality images for different types of graphics -->
<img src="../images/warbler.PNG" alt="Logo" class="logo1" srcset="../images/warbler_2x.PNG 2x">
<img src="../images/warbler.PNG" alt="Logo" class="logo2" srcset="../images/warbler_2x.PNG 2x">
<!-- the header text are animated -->
<h1 class="animate__animated animate__pulse">The Warbler</h1>
<h2 class="animate__animated animate__bounce">Cannabis business locator Ontario Canada</h2>